### PR TITLE
Add additional features and minor fixes

### LINKED ISSUE #132: Create a get_wrapper function
Currently, there is no easy way for users to access the P_ref, Q_ref and V_ref. In the previous version, users just accessed the ext of the DynamicInjection in the system.

A function of the style
```
function get_dynamic_wrapper(sim, name)
    wrappers = sim.inputs.dynamic_injectors
    for w in wrappers
        if PSY.get_name(w) == name
            return w
        end
    end
end
```
allows users to easily access the wrappers by name.

### LINKED ISSUE #133: read_initial_conditions(sim) is failing
Due to the changes on the indexing, there is a bug in the implementation of such function.

### LINKED ISSUE #134: get_P_ref issue with PSID and PSY, and exporting Control Reference Values
Since we are not exporting these functions for the DynamicWrappers it will not work, and users need to write `PSID.get_P_ref(wrapper)` to make it work, since `get_P_ref(wrapper)` is a PSY function.

I think we need to think a way of allowing the users to easily access the control references via a good function that probably export a DataFrame or a Dictionary. Something along the lines of:
```
function get_control_refs(sim, name)
    w = get_dynamic_wrapper(sim, name)
    dic = Dict{String, Float64}()
    dic["P_ref"] = PSID.get_P_ref(w)
    .... # add the other stuff
    return dic
end
```

### PR DESCRIPTION
**Pull request by rodrigomha**
Closes #134 
Closes #133 
Closes #132

### CODE REVIEW

File: src/PowerSimulationsDynamics.jl [hunk 1]
```diff
@@ -33,6 +33,8 @@ export get_real_current_series
 export get_imaginary_current_series
 export get_activepower_series
 export get_reactivepower_series
+export get_dynamic_wrapper
```
Comment (jd-lara) [inline src/PowerSimulationsDynamics.jl:36]: The DynamicWrapper is meant to be an internal object. We should discuss why we would need to export this function.

File: src/base/simulation.jl [hunk 2]
```diff
@@ -398,3 +398,11 @@ end
 function read_results(sim::Simulation)
     return sim.results
 end
+
+function get_dynamic_wrapper(sim::Simulation, name::AbstractString)
+    return get_dynamic_wrapper(get_simulation_inputs(sim), name)
+end
+
+function get_control_references(sim::Simulation)
```
Comment (jd-lara) [inline src/base/simulation.jl:406]: set_points?

File: src/PowerSimulationsDynamics.jl (hunk 1 above)
Comment (rodrigomha) [reply src/PowerSimulationsDynamics.jl:36]: I agree, we may leave the function for us to use for the control references then. The only think that makes sense to output for users is the set points or control references.

**Review by jd-lara — APPROVED** [review]
